FROM ubuntu:22.04

#아래 쉘스크립트 에러 방지 - .bashrc 관련에서 에러
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Update the package lists and install necessary packages
RUN apt-get update && \
    apt-get install -y \
    python3.11 \
	python3-pip \
    vim && \
    apt-get clean && \ 
    rm -rf /var/lib/apt/lists/*

COPY . /project

WORKDIR /project/request-py-slack/app

ENTRYPOINT pip install -r requirements.txt && \
    python3 main.py